[package]
name = "helgoboss-midi"
version = "0.1.0"
authors = ["Benjamin Klum <benjamin.klum@helgoboss.org>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
num_enum = "0.4.2"
strum = "0.18.0"
strum_macros = "0.18.0"
serde = { version = "1.0", optional = true, features = ["derive"] }